### ISSUE TITLE
False positive or malware in release .exe

### ISSUE THREAD

**Issue by lool3** [ayashrath/analyze-whatsapp-chat#1]
The .exe file in the v1.1 release flags up as malicious. It is also contacting some IPs that have been blocked in the past for spreading malware. Sounds like a downloader to me but could be a false positive. Please look into [this](https://www.virustotal.com/gui/file/4682b34f5d25647ab1b31a6bc7a6f2a93aaa5f69941eb0ea944add290fd46e3a?nocache=1), thanks.

**Comment by ayashrath** [comment]
This is indeed a false positive. The anti-virus programs may have flagged it as malicious since the program was compiled into an executable using PyInstaller, and the IP addresses it is communicating with are related to that. It's important to note that PyInstaller is not responsible for introducing malware but can be used to create malicious software. This is probably why the program is being flagged.
